
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Entry entryScalar1;
	
	private global::Gtk.Entry entryScalar2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView textviewScalar;
	
	private global::Gtk.ComboBox comboboxScalar;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.ComboBox comboboxVector;
	
	private global::Gtk.Entry entryVector1_2;
	
	private global::Gtk.Entry entryVector1_3;
	
	private global::Gtk.Entry entryVector1_1;
	
	private global::Gtk.Entry entryVector2_1;
	
	private global::Gtk.Entry entryVector2_2;
	
	private global::Gtk.Entry entryVector2_3;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView textviewVector;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Fixed fixed3;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.ComboBox comboboxMatrix;
	
	private global::Gtk.Entry entryMatrixA_1_1;
	
	private global::Gtk.Entry entryMatrixA_2_1;
	
	private global::Gtk.Entry entryMatrixA_3_1;
	
	private global::Gtk.Entry entryMatrixA_4_1;
	
	private global::Gtk.Entry entryMatrixA_1_2;
	
	private global::Gtk.Entry entryMatrixA_2_2;
	
	private global::Gtk.Entry entryMatrixA_3_2;
	
	private global::Gtk.Entry entryMatrixA_4_2;
	
	private global::Gtk.Entry entryMatrixA_1_3;
	
	private global::Gtk.Entry entryMatrixA_2_3;
	
	private global::Gtk.Entry entryMatrixA_3_3;
	
	private global::Gtk.Entry entryMatrixA_4_3;
	
	private global::Gtk.Entry entryMatrixA_1_4;
	
	private global::Gtk.Entry entryMatrixA_2_4;
	
	private global::Gtk.Entry entryMatrixA_3_4;
	
	private global::Gtk.Entry entryMatrixA_4_4;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.Label labelMatrixResult;
	
	private global::Gtk.Label label3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Składnik 1: ");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w1.X = 4;
		w1.Y = 63;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Składnik 2: ");
		this.fixed1.Add (this.label7);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
		w2.X = 168;
		w2.Y = 62;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entryScalar1 = new global::Gtk.Entry ();
		this.entryScalar1.CanFocus = true;
		this.entryScalar1.Name = "entryScalar1";
		this.entryScalar1.IsEditable = true;
		this.entryScalar1.InvisibleChar = '●';
		this.fixed1.Add (this.entryScalar1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryScalar1]));
		w3.X = 1;
		w3.Y = 82;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entryScalar2 = new global::Gtk.Entry ();
		this.entryScalar2.CanFocus = true;
		this.entryScalar2.Name = "entryScalar2";
		this.entryScalar2.IsEditable = true;
		this.entryScalar2.InvisibleChar = '●';
		this.fixed1.Add (this.entryScalar2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryScalar2]));
		w4.X = 163;
		w4.Y = 82;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 324;
		this.GtkScrolledWindow.HeightRequest = 130;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textviewScalar = new global::Gtk.TextView ();
		this.textviewScalar.CanFocus = true;
		this.textviewScalar.Name = "textviewScalar";
		this.textviewScalar.Editable = false;
		this.GtkScrolledWindow.Add (this.textviewScalar);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w6.X = 1;
		w6.Y = 125;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboboxScalar = global::Gtk.ComboBox.NewText ();
		this.comboboxScalar.AppendText (global::Mono.Unix.Catalog.GetString ("Suma"));
		this.comboboxScalar.AppendText (global::Mono.Unix.Catalog.GetString ("Iloczyn"));
		this.comboboxScalar.AppendText (global::Mono.Unix.Catalog.GetString ("Iloraz"));
		this.comboboxScalar.WidthRequest = 138;
		this.comboboxScalar.Name = "comboboxScalar";
		this.fixed1.Add (this.comboboxScalar);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboboxScalar]));
		w7.X = 164;
		w7.Y = 4;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.TooltipMarkup = "Wybierz rodzaj operacji do wykonania...";
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Operacja:");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w8.X = 101;
		w8.Y = 8;
		this.notebook1.Add (this.fixed1);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Skalary");
		this.notebook1.SetTabLabel (this.fixed1, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Operacja: ");
		this.fixed2.Add (this.label4);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label4]));
		w10.X = 54;
		w10.Y = 9;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.comboboxVector = global::Gtk.ComboBox.NewText ();
		this.comboboxVector.AppendText (global::Mono.Unix.Catalog.GetString ("Suma"));
		this.comboboxVector.AppendText (global::Mono.Unix.Catalog.GetString ("Różnica"));
		this.comboboxVector.AppendText (global::Mono.Unix.Catalog.GetString ("Iloczyn skalarny"));
		this.comboboxVector.AppendText (global::Mono.Unix.Catalog.GetString ("Iloczyn wektorowy"));
		this.comboboxVector.AppendText (global::Mono.Unix.Catalog.GetString ("Długość (wekt. 1)"));
		this.comboboxVector.WidthRequest = 138;
		this.comboboxVector.Name = "comboboxVector";
		this.comboboxVector.Active = 0;
		this.fixed2.Add (this.comboboxVector);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.comboboxVector]));
		w11.X = 121;
		w11.Y = 4;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entryVector1_2 = new global::Gtk.Entry ();
		this.entryVector1_2.WidthRequest = 81;
		this.entryVector1_2.CanFocus = true;
		this.entryVector1_2.Name = "entryVector1_2";
		this.entryVector1_2.IsEditable = true;
		this.entryVector1_2.InvisibleChar = '●';
		this.fixed2.Add (this.entryVector1_2);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entryVector1_2]));
		w12.X = 27;
		w12.Y = 110;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entryVector1_3 = new global::Gtk.Entry ();
		this.entryVector1_3.WidthRequest = 81;
		this.entryVector1_3.CanFocus = true;
		this.entryVector1_3.Name = "entryVector1_3";
		this.entryVector1_3.IsEditable = true;
		this.entryVector1_3.InvisibleChar = '●';
		this.fixed2.Add (this.entryVector1_3);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entryVector1_3]));
		w13.X = 27;
		w13.Y = 140;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entryVector1_1 = new global::Gtk.Entry ();
		this.entryVector1_1.WidthRequest = 81;
		this.entryVector1_1.CanFocus = true;
		this.entryVector1_1.Name = "entryVector1_1";
		this.entryVector1_1.IsEditable = true;
		this.entryVector1_1.InvisibleChar = '●';
		this.fixed2.Add (this.entryVector1_1);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entryVector1_1]));
		w14.X = 27;
		w14.Y = 80;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entryVector2_1 = new global::Gtk.Entry ();
		this.entryVector2_1.WidthRequest = 81;
		this.entryVector2_1.CanFocus = true;
		this.entryVector2_1.Name = "entryVector2_1";
		this.entryVector2_1.IsEditable = true;
		this.entryVector2_1.InvisibleChar = '●';
		this.fixed2.Add (this.entryVector2_1);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entryVector2_1]));
		w15.X = 224;
		w15.Y = 80;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entryVector2_2 = new global::Gtk.Entry ();
		this.entryVector2_2.WidthRequest = 81;
		this.entryVector2_2.CanFocus = true;
		this.entryVector2_2.Name = "entryVector2_2";
		this.entryVector2_2.IsEditable = true;
		this.entryVector2_2.InvisibleChar = '●';
		this.fixed2.Add (this.entryVector2_2);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entryVector2_2]));
		w16.X = 224;
		w16.Y = 110;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entryVector2_3 = new global::Gtk.Entry ();
		this.entryVector2_3.WidthRequest = 81;
		this.entryVector2_3.CanFocus = true;
		this.entryVector2_3.Name = "entryVector2_3";
		this.entryVector2_3.IsEditable = true;
		this.entryVector2_3.InvisibleChar = '●';
		this.fixed2.Add (this.entryVector2_3);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entryVector2_3]));
		w17.X = 224;
		w17.Y = 140;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Wektor 1:");
		this.fixed2.Add (this.label8);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label8]));
		w18.X = 30;
		w18.Y = 57;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Wektor 2:");
		this.fixed2.Add (this.label9);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label9]));
		w19.X = 227;
		w19.Y = 56;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.WidthRequest = 319;
		this.GtkScrolledWindow1.HeightRequest = 90;
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textviewVector = new global::Gtk.TextView ();
		this.textviewVector.CanFocus = true;
		this.textviewVector.Name = "textviewVector";
		this.GtkScrolledWindow1.Add (this.textviewVector);
		this.fixed2.Add (this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.GtkScrolledWindow1]));
		w21.X = 3;
		w21.Y = 177;
		this.notebook1.Add (this.fixed2);
		global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.fixed2]));
		w22.Position = 1;
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Wektory");
		this.notebook1.SetTabLabel (this.fixed2, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Operacja:");
		this.fixed3.Add (this.label10);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label10]));
		w23.X = 57;
		w23.Y = 12;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.comboboxMatrix = global::Gtk.ComboBox.NewText ();
		this.comboboxMatrix.AppendText (global::Mono.Unix.Catalog.GetString ("Suma"));
		this.comboboxMatrix.AppendText (global::Mono.Unix.Catalog.GetString ("Iloczyn"));
		this.comboboxMatrix.AppendText (global::Mono.Unix.Catalog.GetString ("Suma elementów (Macierz 1)"));
		this.comboboxMatrix.WidthRequest = 138;
		this.comboboxMatrix.Name = "comboboxMatrix";
		this.fixed3.Add (this.comboboxMatrix);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.comboboxMatrix]));
		w24.X = 121;
		w24.Y = 6;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_1_1 = new global::Gtk.Entry ();
		this.entryMatrixA_1_1.WidthRequest = 36;
		this.entryMatrixA_1_1.CanFocus = true;
		this.entryMatrixA_1_1.Name = "entryMatrixA_1_1";
		this.entryMatrixA_1_1.IsEditable = true;
		this.entryMatrixA_1_1.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_1_1);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_1_1]));
		w25.X = 3;
		w25.Y = 62;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_2_1 = new global::Gtk.Entry ();
		this.entryMatrixA_2_1.WidthRequest = 36;
		this.entryMatrixA_2_1.CanFocus = true;
		this.entryMatrixA_2_1.Name = "entryMatrixA_2_1";
		this.entryMatrixA_2_1.IsEditable = true;
		this.entryMatrixA_2_1.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_2_1);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_2_1]));
		w26.X = 3;
		w26.Y = 96;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_3_1 = new global::Gtk.Entry ();
		this.entryMatrixA_3_1.WidthRequest = 36;
		this.entryMatrixA_3_1.CanFocus = true;
		this.entryMatrixA_3_1.Name = "entryMatrixA_3_1";
		this.entryMatrixA_3_1.IsEditable = true;
		this.entryMatrixA_3_1.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_3_1);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_3_1]));
		w27.X = 3;
		w27.Y = 130;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_4_1 = new global::Gtk.Entry ();
		this.entryMatrixA_4_1.WidthRequest = 36;
		this.entryMatrixA_4_1.CanFocus = true;
		this.entryMatrixA_4_1.Name = "entryMatrixA_4_1";
		this.entryMatrixA_4_1.IsEditable = true;
		this.entryMatrixA_4_1.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_4_1);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_4_1]));
		w28.X = 3;
		w28.Y = 164;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_1_2 = new global::Gtk.Entry ();
		this.entryMatrixA_1_2.WidthRequest = 36;
		this.entryMatrixA_1_2.CanFocus = true;
		this.entryMatrixA_1_2.Name = "entryMatrixA_1_2";
		this.entryMatrixA_1_2.IsEditable = true;
		this.entryMatrixA_1_2.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_1_2);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_1_2]));
		w29.X = 44;
		w29.Y = 62;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_2_2 = new global::Gtk.Entry ();
		this.entryMatrixA_2_2.WidthRequest = 36;
		this.entryMatrixA_2_2.CanFocus = true;
		this.entryMatrixA_2_2.Name = "entryMatrixA_2_2";
		this.entryMatrixA_2_2.IsEditable = true;
		this.entryMatrixA_2_2.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_2_2);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_2_2]));
		w30.X = 44;
		w30.Y = 96;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_3_2 = new global::Gtk.Entry ();
		this.entryMatrixA_3_2.WidthRequest = 36;
		this.entryMatrixA_3_2.CanFocus = true;
		this.entryMatrixA_3_2.Name = "entryMatrixA_3_2";
		this.entryMatrixA_3_2.IsEditable = true;
		this.entryMatrixA_3_2.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_3_2);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_3_2]));
		w31.X = 44;
		w31.Y = 130;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_4_2 = new global::Gtk.Entry ();
		this.entryMatrixA_4_2.WidthRequest = 36;
		this.entryMatrixA_4_2.CanFocus = true;
		this.entryMatrixA_4_2.Name = "entryMatrixA_4_2";
		this.entryMatrixA_4_2.IsEditable = true;
		this.entryMatrixA_4_2.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_4_2);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_4_2]));
		w32.X = 44;
		w32.Y = 164;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_1_3 = new global::Gtk.Entry ();
		this.entryMatrixA_1_3.WidthRequest = 36;
		this.entryMatrixA_1_3.CanFocus = true;
		this.entryMatrixA_1_3.Name = "entryMatrixA_1_3";
		this.entryMatrixA_1_3.IsEditable = true;
		this.entryMatrixA_1_3.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_1_3);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_1_3]));
		w33.X = 87;
		w33.Y = 62;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_2_3 = new global::Gtk.Entry ();
		this.entryMatrixA_2_3.WidthRequest = 36;
		this.entryMatrixA_2_3.CanFocus = true;
		this.entryMatrixA_2_3.Name = "entryMatrixA_2_3";
		this.entryMatrixA_2_3.IsEditable = true;
		this.entryMatrixA_2_3.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_2_3);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_2_3]));
		w34.X = 87;
		w34.Y = 96;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_3_3 = new global::Gtk.Entry ();
		this.entryMatrixA_3_3.WidthRequest = 36;
		this.entryMatrixA_3_3.CanFocus = true;
		this.entryMatrixA_3_3.Name = "entryMatrixA_3_3";
		this.entryMatrixA_3_3.IsEditable = true;
		this.entryMatrixA_3_3.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_3_3);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_3_3]));
		w35.X = 87;
		w35.Y = 131;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_4_3 = new global::Gtk.Entry ();
		this.entryMatrixA_4_3.WidthRequest = 36;
		this.entryMatrixA_4_3.CanFocus = true;
		this.entryMatrixA_4_3.Name = "entryMatrixA_4_3";
		this.entryMatrixA_4_3.IsEditable = true;
		this.entryMatrixA_4_3.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_4_3);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_4_3]));
		w36.X = 87;
		w36.Y = 165;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_1_4 = new global::Gtk.Entry ();
		this.entryMatrixA_1_4.WidthRequest = 36;
		this.entryMatrixA_1_4.CanFocus = true;
		this.entryMatrixA_1_4.Name = "entryMatrixA_1_4";
		this.entryMatrixA_1_4.IsEditable = true;
		this.entryMatrixA_1_4.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_1_4);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_1_4]));
		w37.X = 132;
		w37.Y = 62;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_2_4 = new global::Gtk.Entry ();
		this.entryMatrixA_2_4.WidthRequest = 36;
		this.entryMatrixA_2_4.CanFocus = true;
		this.entryMatrixA_2_4.Name = "entryMatrixA_2_4";
		this.entryMatrixA_2_4.IsEditable = true;
		this.entryMatrixA_2_4.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_2_4);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_2_4]));
		w38.X = 132;
		w38.Y = 96;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_3_4 = new global::Gtk.Entry ();
		this.entryMatrixA_3_4.WidthRequest = 36;
		this.entryMatrixA_3_4.CanFocus = true;
		this.entryMatrixA_3_4.Name = "entryMatrixA_3_4";
		this.entryMatrixA_3_4.IsEditable = true;
		this.entryMatrixA_3_4.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_3_4);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_3_4]));
		w39.X = 132;
		w39.Y = 131;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entryMatrixA_4_4 = new global::Gtk.Entry ();
		this.entryMatrixA_4_4.WidthRequest = 36;
		this.entryMatrixA_4_4.CanFocus = true;
		this.entryMatrixA_4_4.Name = "entryMatrixA_4_4";
		this.entryMatrixA_4_4.IsEditable = true;
		this.entryMatrixA_4_4.InvisibleChar = '●';
		this.fixed3.Add (this.entryMatrixA_4_4);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entryMatrixA_4_4]));
		w40.X = 132;
		w40.Y = 165;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Macierz 1:");
		this.fixed3.Add (this.label11);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label11]));
		w41.X = 4;
		w41.Y = 39;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.labelMatrixResult = new global::Gtk.Label ();
		this.labelMatrixResult.Name = "labelMatrixResult";
		this.labelMatrixResult.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
		this.fixed3.Add (this.labelMatrixResult);
		global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.labelMatrixResult]));
		w42.X = 6;
		w42.Y = 221;
		this.notebook1.Add (this.fixed3);
		global::Gtk.Notebook.NotebookChild w43 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.fixed3]));
		w43.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Macierze");
		this.notebook1.SetTabLabel (this.fixed3, this.label3);
		this.label3.ShowAll ();
		this.Add (this.notebook1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 329;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.entryScalar1.Changed += new global::System.EventHandler (this.changedScalarA);
		this.entryScalar2.Changed += new global::System.EventHandler (this.changedScalarB);
		this.entryVector1_1.Changed += new global::System.EventHandler (this.changedVectorA_1);
		this.entryVector1_2.Changed += new global::System.EventHandler (this.changedVectorA_2);
		this.entryVector1_3.Changed += new global::System.EventHandler (this.changedVectorA_3);
		this.entryVector2_1.Changed += new global::System.EventHandler (this.changedVectorB_1);
		this.entryVector2_1.Changed += new global::System.EventHandler (this.changedVectorB_2);
		this.entryVector2_1.Changed += new global::System.EventHandler (this.changedVectorB_3);
		//////////////////////////////////////////
		/// 
		/// Tekstowo szybciej jest uzupełnić przypisanie zdarzeń, a przy macierzy będziemy mieli
		/// 32 TextBoxy! ;)
		/// 
		//
		this.comboboxScalar.Changed += new global::System.EventHandler (this.setOperationScalar);
		this.comboboxVector.Changed += new global::System.EventHandler (this.setOperationVector);
		this.comboboxMatrix.Changed += new global::System.EventHandler (this.setOperationMatrix);
	}
}
